# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-10 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, verbose_name='普文目录名')),
            ],
            options={
                'verbose_name': '1.2谱文目录表',
                'db_table': 'ge_article_catalogue',
                'verbose_name_plural': '1.2谱文目录表',
            },
        ),
        migrations.CreateModel(
            name='GeneBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=256, verbose_name='谱书名')),
                ('desc', models.TextField(blank=True, max_length=256, null=True, verbose_name='谱书简介')),
                ('img', models.ImageField(blank=True, null=True, upload_to='family', verbose_name='谱书封面存储地址')),
                ('img_name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='谱书封面')),
                ('author', models.CharField(blank=True, default=None, max_length=256, verbose_name='修撰者')),
                ('addr', models.CharField(blank=True, default=None, max_length=256, verbose_name='所属地区')),
                ('province', models.CharField(blank=True, default=None, max_length=256, verbose_name='省')),
                ('city', models.CharField(blank=True, default=None, max_length=256, verbose_name='市')),
                ('district', models.CharField(blank=True, default=None, max_length=256, verbose_name='县/区')),
                ('grant', models.BooleanField(choices=[(0, '公开'), (1, '私密')], default=0, verbose_name='权限')),
                ('audit_status', models.SmallIntegerField(choices=[(1, '未发布'), (2, '审核中'), (3, '已发布'), (4, '审核不通过')], default=1, verbose_name='谱书状态')),
            ],
            options={
                'verbose_name': '1.0谱书信息表',
                'db_table': 'ge_gene_book',
                'verbose_name_plural': '1.0谱书信息表',
            },
        ),
        migrations.CreateModel(
            name='ImgsCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, verbose_name='图像目录名')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.GeneBook', verbose_name='所属谱书')),
            ],
            options={
                'verbose_name': '1.1图像目录表',
                'db_table': 'ge_imgs_catalogue',
                'verbose_name_plural': '1.1图像目录表',
            },
        ),
        migrations.CreateModel(
            name='ZtreeCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, verbose_name='世系目录名')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.GeneBook', verbose_name='所属谱书')),
            ],
            options={
                'verbose_name': '1.3世系目录表',
                'db_table': 'ge_ztree_catalogue',
                'verbose_name_plural': '1.3世系目录表',
            },
        ),
    ]
