# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-10 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genebook',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='articlecatalogue',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.GeneBook', verbose_name='所属谱书'),
        ),
    ]
