# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-13 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_auto_20190510_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='genebook',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='文章阅读量'),
        ),
        migrations.AlterField(
            model_name='genebook',
            name='img_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='谱书封面'),
        ),
    ]
