# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190513_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='addr',
            field=models.CharField(blank=True, default='神州大地', max_length=256, null=True, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='头像名称'),
        ),
    ]
