# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-10 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=256, verbose_name='谱文标题')),
                ('content', tinymce.models.HTMLField()),
                ('book_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.GeneBook', verbose_name='所属谱书')),
                ('catalogue_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.ArticleCatalogue', verbose_name='所属目录')),
            ],
            options={
                'verbose_name': '谱文',
                'db_table': 'ge_article',
                'verbose_name_plural': '谱文',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('file', models.FileField(default=None, null=True, upload_to='files', verbose_name='图片地址')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='文件名称')),
            ],
            options={
                'verbose_name': '文件',
                'db_table': 'ge_files',
                'verbose_name_plural': '文件',
            },
        ),
        migrations.CreateModel(
            name='FilesDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=10, verbose_name='文件库名称/标题')),
                ('book_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.GeneBook', verbose_name='所属谱书')),
                ('catalogue_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.ArticleCatalogue', verbose_name='所属目录')),
            ],
            options={
                'verbose_name': '文件库',
                'db_table': 'ge_files_database',
                'verbose_name_plural': '文件库',
            },
        ),
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('img', models.ImageField(default=None, null=True, upload_to='imgs', verbose_name='图片地址')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='图片名称')),
                ('detail', models.CharField(default='', max_length=200, verbose_name='图片描述信息')),
            ],
            options={
                'verbose_name': '图片',
                'db_table': 'ge_imgs',
                'verbose_name_plural': '图片',
            },
        ),
        migrations.CreateModel(
            name='ImgsDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=10, verbose_name='图片库名称/标题')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.GeneBook', verbose_name='所属谱书')),
                ('catalogue_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.ImgsCatalogue', verbose_name='所属目录')),
            ],
            options={
                'verbose_name': '图片库',
                'db_table': 'ge_imgs_database',
                'verbose_name_plural': '图片库',
            },
        ),
        migrations.CreateModel(
            name='NodePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('last_name', models.CharField(max_length=10, verbose_name='姓氏')),
                ('first_name', models.CharField(max_length=10, verbose_name='名')),
                ('other_name', models.CharField(blank=True, max_length=5, null=True, verbose_name='字')),
                ('seniority', models.SmallIntegerField(choices=[(1, '独生子'), (2, '独生女'), (3, '第一'), (4, '第二'), (5, '第三'), (6, '第四'), (7, '第五'), (8, '第六'), (9, '第七'), (10, '第八'), (11, '第九'), (12, '第十'), (13, '第十一'), (14, '第十二')], default=1, verbose_name='排行')),
                ('sex', models.BooleanField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('spouse', models.CharField(blank=True, max_length=20, null=True, verbose_name='配偶')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('deathdate', models.DateField(blank=True, null=True, verbose_name='死亡日期')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='人物简介')),
            ],
            options={
                'verbose_name': '世系节点人物表',
                'db_table': 'ge_node_person',
                'verbose_name_plural': '世系节点人物表',
            },
        ),
        migrations.CreateModel(
            name='Ztree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=100, verbose_name='世系表名')),
                ('book_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.GeneBook', verbose_name='所属谱书')),
                ('catalogue_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.ZtreeCatalogue', verbose_name='所属目录')),
            ],
            options={
                'verbose_name': '世系信息表',
                'db_table': 'ge_ztree',
                'verbose_name_plural': '世系信息表',
            },
        ),
        migrations.CreateModel(
            name='ZtreeNode',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False, verbose_name='人物id')),
                ('name', models.CharField(max_length=20, verbose_name='人物姓名')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file.ZtreeNode', verbose_name='父亲')),
                ('ztree_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.Ztree', verbose_name='所属世系表')),
            ],
            options={
                'verbose_name': '世系节点表',
                'db_table': 'ge_ztree_node',
                'verbose_name_plural': '世系节点表',
            },
        ),
        migrations.AddField(
            model_name='nodeperson',
            name='node_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file.ZtreeNode', verbose_name='对应世系节点'),
        ),
        migrations.AddField(
            model_name='imgs',
            name='imgsdb_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='file.ImgsDatabase', verbose_name='所属图片库'),
        ),
        migrations.AddField(
            model_name='files',
            name='filesdb_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='file.FilesDatabase', verbose_name='所属文件库'),
        ),
    ]
