# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='文件名称'),
        ),
        migrations.AlterField(
            model_name='filesdatabase',
            name='name',
            field=models.CharField(max_length=256, verbose_name='文件库名称/标题'),
        ),
        migrations.AlterField(
            model_name='imgs',
            name='detail',
            field=models.TextField(default='', verbose_name='图片描述信息'),
        ),
        migrations.AlterField(
            model_name='imgs',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='imgsdatabase',
            name='name',
            field=models.CharField(max_length=256, verbose_name='图片库名称/标题'),
        ),
        migrations.AlterField(
            model_name='nodeperson',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='nodeperson',
            name='last_name',
            field=models.CharField(max_length=256, verbose_name='姓氏'),
        ),
        migrations.AlterField(
            model_name='nodeperson',
            name='other_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='字'),
        ),
        migrations.AlterField(
            model_name='nodeperson',
            name='spouse',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='配偶'),
        ),
        migrations.AlterField(
            model_name='ztree',
            name='name',
            field=models.CharField(max_length=256, verbose_name='世系表名'),
        ),
        migrations.AlterField(
            model_name='ztreenode',
            name='id',
            field=models.AutoField(max_length=256, primary_key=True, serialize=False, verbose_name='人物id'),
        ),
        migrations.AlterField(
            model_name='ztreenode',
            name='name',
            field=models.CharField(max_length=256, verbose_name='人物姓名'),
        ),
    ]
