# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturearticle',
            name='author',
            field=models.CharField(max_length=256, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='culturearticle',
            name='title',
            field=models.CharField(max_length=256, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='culturecategory',
            name='name',
            field=models.CharField(max_length=256, verbose_name='文章类别'),
        ),
    ]
